name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for your interest by sharing what's going wrong with Rasengan.js, your contribution will help more than one."
          pr-message: 'Oh nice, this is your first pull request on Rasengan.js repository. Thanks for contributing to the project.'
